plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'signing'
    id "com.gradle.plugin-publish" version "1.3.1"
}

apply plugin: 'groovy'

def env = System.getProperty("profile") ?: "maven"

apply from: "profile-${env}.gradle"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}
