buildscript {
    repositories {
        mavenCentral()
    }
}

apply plugin: 'maven-publish'

dependencies {
    implementation gradleApi()
    implementation localGroovy()
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}

tasks.register('javadocJar', Jar) {
    from javadoc
    archiveClassifier = 'javadoc'
}

javadoc {
    if (JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
    if (JavaVersion.current().isJava8Compatible()) {
        options.addStringOption('Xdoclint:none', '-quiet')
    }
    options {
        encoding "UTF-8"
        charSet 'UTF-8'
        author true
        version true
    }
}

def getRepositoryUsername() {
    return hasProperty('oss_username') ? oss_username : ""
}

def getRepositoryPassword() {
    return hasProperty('oss_password') ? oss_password : ""
}

publishing {
    publications {
        named('pluginMaven', MavenPublication) {
            artifact tasks.named('sourcesJar')
            artifact tasks.named('javadocJar')
            pom {
                name = 'lodsve archetype'
                description = 'Gradle plugin that creates projects from your own cookie cutter'
                url = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'
                licenses {
                    license {
                        name = 'GNU General Public License version 3'
                        url = 'https://opensource.org/licenses/GPL-3.0'
                    }
                }
                developers {
                    developer {
                        id = 'sunhao'
                        name = '孙昊'
                        email = 'sunhao.java@gmail.com'
                    }
                }
                scm {
                    url = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'
                    connection = 'scm:git:git@github.com:lodsve/lodsve-gradle-archetype-plugin.git'
                    developerConnection = 'scm:git:git@github.com:lodsve/lodsve-gradle-archetype-plugin.git'
                }
            }
        }
    }
    repositories {
        maven {
            name = 'sonatype'
            url = uri(project.version.toString().endsWith('SNAPSHOT')
                    ? 'https://oss.sonatype.org/content/repositories/snapshots/'
                    : 'https://oss.sonatype.org/service/local/staging/deploy/maven2/')
            credentials {
                username = getRepositoryUsername()
                password = getRepositoryPassword()
            }
        }
    }
}

signing {
    required { gradle.taskGraph.hasTask('publish') }
    sign publishing.publications
}
