
dependencies {
    implementation gradleApi()
    implementation localGroovy()
}

pluginBundle {
    website = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'
    vcsUrl = 'https://github.com/lodsve/lodsve-gradle-archetype-plugin'

    description = 'Gradle plugin that generate projects from template.'
    tags = ['archetype', 'template']

    plugins {
        plugin {
            id = 'com.lodsve.archetype'
            displayName = 'Archetype Generate Plugin'
            version = project.version
        }
    }
}
